#include <stdio.h>
#include <stdlib.h>
#include "include/fortune.h"
#include "include/queue.h"
#include "include/geometry.h"
#include "include/beachline.h"


/* FROM: CMSC 754: Lecture 11, Voronoi Diagrams and Fortune’s Algorithm, Dave Mount, Spring 2020
 *
 * Site event:  Sweep line passes over a new site.
 *                - The new site has a degenerate arc (vertical line). Assume
 *                  it does not fall immeadetly below an existing vertex.
 *                - The existing arch is then split into three:
 *                  < ... pi ... >    ->    < ... pi pj pi ... >
 *                - Note that these events are known in advance!
 *
 * Vertex event:  Generated by adjacent arcs, once one "disappears".
 *                  - Consider pi, pj, pk sucht that: 
 *                    < ... pj pi pj pk ... >  .
 *                    There is a circumcircle containint these 3 points.
 *                  - If the circumcircle does not contain any other site 
 *                    inside (bellow the sweep-line), no future point will 
 *                    block the creation of the vertex.
 *                  - The vertex is created when the sweep-liine reaches the
 *                    lowest point of the circumcircle.
 *                  - The bisectors (pi, pj) and (pj, pk) have met each other.
 *                    Now a new bisector (pi, pk) is created.
 *                    < .. pj pi pj pk .. >    ->    < .. pj pi pk .. >
*/


vor_diagram_T *fortune_algorithm(point2D_T *seeds, int N)
{
  queue_T queue = initialize_queue(seeds, N);

  vor_diagram_T *diagram = NULL;
  beachline_T bline = NULL;

  while (queue) {
    event_T event = pop_event(&queue);
    putchar('\n');
    print_event(&event);
    print_queue(queue);
    print_beachline(bline);

    if (event.type == EVENT_SITE) {
      arc_T *arc = insert_arc(&bline, event.p);
      remove_vertex_events_involving(&queue, arc->left);
      add_vertex_events_involving(&queue, arc);
      
    } else if (event.type == EVENT_VERTEX) {
      arc_T *left = event.arc->left; 
      arc_T *right = event.arc->right;
      remove_vertex_events_involving(&queue, event.arc);
      delete_arc(&bline, event.arc);
      if (left) add_vertex_events_involving(&queue, left);
      if (right) add_vertex_events_involving(&queue, right);

    } else {
      printf("ERROR! Unknown event! Should never see this...\n");
      exit(1);
    }
 }

  print_beachline(bline);
  free_beachline(bline);

  return diagram;
}


